---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout #checkout source code to working directory
      - run:
          name: Install Packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip python3 python-pip -y
      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            aws configure set default.region us-east-1
      - run:
          name: Build Artifact
          command: |
            pwd
            ls -al
            cd WebApplication
            mvn clean install
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "Current Build Number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codeDeploy_Artifact
            cd codeDeploy_Artifact
            cp ../webapp/*yml .
            cp ../WebApplication/target/WebApplication-0.0.1-SNAPSHOT.jar .
            cp ../WebApplication/src/main/resources/*.properties .
            ls -al
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip
            rm *.yml *.sh *.properties *.jar
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artficat to S3 Bucket
          command: aws s3 cp --recursive codeDeploy_Artifact s3://${CODE_DEPLOY_S3_BUCKET}
      - run:
          name: step into webapp and execute test
          command: |
            cd WebApplication
            mvn clean install
            mvn test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout #checkout source code to working directory
      - run:
          name: step into webapp
          command: |
            cd WebApplication
            mvn clean install
            mvn test

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
